"""add users columns

Revision ID: 93850df0ca87
Revises: ea3bb62e7202
Create Date: 2025-07-23 09:16:24.846474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93850df0ca87'
down_revision = 'ea3bb62e7202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_clients_phone_number'))
        batch_op.drop_index(batch_op.f('idx_clients_user_id'))
        batch_op.drop_index(batch_op.f('idx_clients_user_phone'))
        batch_op.drop_table_comment(
        existing_comment='End customers/contacts that businesses communicate with'
    )

    with op.batch_alter_table('message_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_templates_user_id'))
        batch_op.drop_table_comment(
        existing_comment='Reusable message templates for quick replies'
    )

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_messages_user_id'))
        batch_op.drop_table_comment(
        existing_comment='SMS messages sent and received through the platform'
    )

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='User subscription and billing information'
    )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trial', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('trial_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('trial_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('trial_end_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('trial_days_remaining', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('trial_expired_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('trial_converted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('signalwire_setup_pending', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('signalwire_setup_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('signalwire_subproject_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('signalwire_auth_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('signalwire_phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('signalwire_phone_sid', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('signalwire_number_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('subscription_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('subscription_plan_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('subscription_activated_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_users_active'))
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_table_comment(
        existing_comment='Business owners/customers who use the SMS AI platform'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Business owners/customers who use the SMS AI platform',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_active'), ['is_active'], unique=False)
        batch_op.drop_column('subscription_activated_at')
        batch_op.drop_column('subscription_plan_id')
        batch_op.drop_column('subscription_active')
        batch_op.drop_column('signalwire_number_active')
        batch_op.drop_column('signalwire_phone_sid')
        batch_op.drop_column('signalwire_phone_number')
        batch_op.drop_column('signalwire_auth_token')
        batch_op.drop_column('signalwire_subproject_id')
        batch_op.drop_column('signalwire_setup_completed')
        batch_op.drop_column('signalwire_setup_pending')
        batch_op.drop_column('trial_converted_at')
        batch_op.drop_column('trial_expired_at')
        batch_op.drop_column('trial_days_remaining')
        batch_op.drop_column('trial_end_date')
        batch_op.drop_column('trial_start_date')
        batch_op.drop_column('trial_status')
        batch_op.drop_column('is_trial')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_table_comment(
        'User subscription and billing information',
        existing_comment=None
    )

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_table_comment(
        'SMS messages sent and received through the platform',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_messages_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('message_templates', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Reusable message templates for quick replies',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_templates_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_table_comment(
        'End customers/contacts that businesses communicate with',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_clients_user_phone'), ['user_id', 'phone_number'], unique=False)
        batch_op.create_index(batch_op.f('idx_clients_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_clients_phone_number'), ['phone_number'], unique=False)

    # ### end Alembic commands ###
