"""initial migrate

Revision ID: d2f924302c45
Revises: 
Create Date: 2025-06-06 14:44:24.171797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f924302c45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_regular', sa.Boolean(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('first_contact', sa.DateTime(), nullable=True),
    sa.Column('last_contact', sa.DateTime(), nullable=True),
    sa.Column('last_ai_response', sa.DateTime(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('preferred_communication_time', sa.String(length=50), nullable=True),
    sa.Column('response_preference', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('system_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('backend_status', sa.String(length=20), nullable=True),
    sa.Column('llm_server_status', sa.String(length=20), nullable=True),
    sa.Column('database_status', sa.String(length=20), nullable=True),
    sa.Column('redis_status', sa.String(length=20), nullable=True),
    sa.Column('signalwire_status', sa.String(length=20), nullable=True),
    sa.Column('response_time_p95', sa.Float(), nullable=True),
    sa.Column('memory_usage_percent', sa.Float(), nullable=True),
    sa.Column('cpu_usage_percent', sa.Float(), nullable=True),
    sa.Column('disk_usage_percent', sa.Float(), nullable=True),
    sa.Column('celery_queue_length', sa.Integer(), nullable=True),
    sa.Column('celery_failed_tasks', sa.Integer(), nullable=True),
    sa.Column('webhook_error_rate', sa.Float(), nullable=True),
    sa.Column('ai_generation_error_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('twilio_account_sid', sa.String(length=50), nullable=True),
    sa.Column('twilio_api_key_sid', sa.String(length=50), nullable=True),
    sa.Column('twilio_account_type', sa.String(length=20), nullable=True),
    sa.Column('twilio_parent_account', sa.Boolean(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('_twilio_auth_token', sa.String(length=255), nullable=True),
    sa.Column('_twilio_api_key_secret', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('ai_enabled', sa.Boolean(), nullable=True),
    sa.Column('business_hours', sa.Text(), nullable=True),
    sa.Column('daily_auto_response_limit', sa.Integer(), nullable=True),
    sa.Column('signalwire_sid', sa.String(length=50), nullable=True),
    sa.Column('webhook_configured', sa.Boolean(), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('total_messages_received', sa.Integer(), nullable=True),
    sa.Column('total_ai_responses_sent', sa.Integer(), nullable=True),
    sa.Column('avg_response_time', sa.Float(), nullable=True),
    sa.Column('auto_moderation_enabled', sa.Boolean(), nullable=True),
    sa.Column('strict_safety_mode', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('ai_model_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('response_length', sa.Integer(), nullable=True),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('style_notes', sa.Text(), nullable=True),
    sa.Column('safety_level', sa.String(length=20), nullable=True),
    sa.Column('content_filter_enabled', sa.Boolean(), nullable=True),
    sa.Column('response_timeout', sa.Integer(), nullable=True),
    sa.Column('retry_attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sender_number', sa.String(length=20), nullable=False),
    sa.Column('is_incoming', sa.Boolean(), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('signalwire_sid', sa.String(length=50), nullable=True),
    sa.Column('send_status', sa.String(length=20), nullable=True),
    sa.Column('send_error', sa.Text(), nullable=True),
    sa.Column('status_updated_at', sa.DateTime(), nullable=True),
    sa.Column('ai_model_used', sa.String(length=50), nullable=True),
    sa.Column('ai_processing_time', sa.Float(), nullable=True),
    sa.Column('ai_fallback_used', sa.Boolean(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=True),
    sa.Column('conversation_turn', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('out_of_office_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('relationship_status', sa.String(length=50), nullable=True),
    sa.Column('last_interaction', sa.DateTime(), nullable=True),
    sa.Column('total_interactions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_incoming', sa.Boolean(), nullable=False),
    sa.Column('context_note', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('messages_received', sa.Integer(), nullable=True),
    sa.Column('messages_sent', sa.Integer(), nullable=True),
    sa.Column('ai_responses', sa.Integer(), nullable=True),
    sa.Column('auto_responses', sa.Integer(), nullable=True),
    sa.Column('avg_response_time', sa.Float(), nullable=True),
    sa.Column('llm_server_requests', sa.Integer(), nullable=True),
    sa.Column('llm_server_failures', sa.Integer(), nullable=True),
    sa.Column('openai_fallback_usage', sa.Integer(), nullable=True),
    sa.Column('flagged_messages', sa.Integer(), nullable=True),
    sa.Column('blocked_responses', sa.Integer(), nullable=True),
    sa.Column('high_risk_interactions', sa.Integer(), nullable=True),
    sa.Column('unique_contacts', sa.Integer(), nullable=True),
    sa.Column('conversation_starts', sa.Integer(), nullable=True),
    sa.Column('conversation_length_avg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flagged_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('reasons', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('detection_method', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('response_blocked', sa.Boolean(), nullable=True),
    sa.Column('auto_response_sent', sa.String(length=500), nullable=True),
    sa.Column('flagged_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flagged_messages')
    op.drop_table('usage_metrics')
    op.drop_table('text_examples')
    op.drop_table('profile_clients')
    op.drop_table('out_of_office_replies')
    op.drop_table('messages')
    op.drop_table('auto_replies')
    op.drop_table('ai_model_settings')
    op.drop_table('profiles')
    op.drop_table('users')
    op.drop_table('system_health')
    op.drop_table('clients')
    # ### end Alembic commands ###
