"""fixed client messages

Revision ID: ea3bb62e7202
Revises: c0bd1cek643
Create Date: 2025-07-20 14:10:21.824714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea3bb62e7202'
down_revision = 'c0bd1cek643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('idx_messages_client_id')
        batch_op.drop_constraint('fk_messages_client_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clients', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_messages_client_id', 'clients', ['client_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index('idx_messages_client_id', ['client_id'], unique=False)

    # ### end Alembic commands ###
